### ISSUE TITLE
Handle generics better

### ISSUE THREAD

**Issue by staktrace** [jrmuizel/wr-binding#2]
Right now the binding generator attempts to convert generic types in Rust to templates in the .h file. I thought this would work, but it doesn't because the .h file is extern "C" (as opposed to C++) and so templates are disallowed. We need to figure out a better way to convert generic types into concrete types.

**Comment by eqrion** [comment]
A solution for this could be to use `type x = y` definitions, to specify names for fully specified generics.

Then for each of these we would generate a struct with the generic parameters filled in. This is similar to the type aliasing support already so it could fit well. We would then disallow using generics not behind type aliases everywhere.

I was looking at implementing this.

**Comment by staktrace** [comment]
That sounds like a good idea!
