### ISSUE TITLE
Decide if we want to move this project into the mozilla-central tree

### ISSUE THREAD

**Issue by staktrace** [jrmuizel/wr-binding#8]
If we want to autogenerate the bindings file during the build, then we'll want to move this project into mozilla-central. This is relatively painless, I cooked up a [patch to do it](https://github.com/staktrace/gecko-dev/commit/d9b23bc4f51beccc002d70aa159f830cf2ded75a) (the interesting part is [here](https://github.com/staktrace/gecko-dev/commit/d9b23bc4f51beccc002d70aa159f830cf2ded75a#diff-483d61608cf0415cf961b4dd0563cf2b)).

On the other hand, if we want flesh this out into a more standalone project that can be used for other (non-mozilla) binding generation we can go that way, and try to remove the WR-specific stuff from the project.

@rlhunt @jrmuizel thoughts?

**Comment by staktrace** [comment]
Also, unrelatedly - the binding generator runs *so* much faster in release mode (which is what it gets built in with the patch I linked above). At lightning speed it's not even worth adding the multithreading-ness I had in mind.

**Comment by eqrion** [comment]
I would like to flesh this out into a standalone project, possibly rename it to cbindgen. If this happens, people would be able to grab it using `cargo install cbindgen`, which might make it easier for building the bindings. I also see no problem with checking in a stable version into m-c to use for building bindings.

**Comment by staktrace** [comment]
This happened.
